require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AppartmentsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Appartment. As you add validations to Appartment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { attributes_for :appartment }

  let(:invalid_attributes) { attributes_for :appartment, name: '' }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AppartmentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all appartments as @appartments" do
      appartment = Appartment.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:appartments)).to eq([appartment])
    end
  end

  describe "GET #show" do
    it "assigns the requested appartment as @appartment" do
      appartment = Appartment.create! valid_attributes
      get :show,  {id: appartment.to_param}, session: valid_session
      expect(assigns(:appartment)).to eq(appartment)
    end
  end

  describe "GET #new" do
    it "assigns a new appartment as @appartment" do
      get :new, params: {}, session: valid_session
      expect(assigns(:appartment)).to be_a_new(Appartment)
    end
  end

  describe "GET #edit" do
    it "assigns the requested appartment as @appartment" do
      appartment = Appartment.create! valid_attributes
      get :edit,  {id: appartment.to_param}, session: valid_session
      expect(assigns(:appartment)).to eq(appartment)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Appartment" do
        expect {
          post :create,  {appartment: valid_attributes}, session: valid_session
        }.to change(Appartment, :count).by(1)
      end

      it "assigns a newly created appartment as @appartment" do
        post :create,  {appartment: valid_attributes}, session: valid_session
        expect(assigns(:appartment)).to be_a(Appartment)
        expect(assigns(:appartment)).to be_persisted
      end

      it "redirects to the created appartment" do
        post :create,  {appartment: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Appartment.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved appartment as @appartment" do
        post :create,  {appartment: invalid_attributes}, session: valid_session
        expect(assigns(:appartment)).to be_a_new(Appartment)
      end

      it "re-renders the 'new' template" do
        post :create,  {appartment: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) { attributes_for :appartment, name: 'Hiboux' }

      it "updates the requested appartment" do
        appartment = Appartment.create! valid_attributes
        put :update,  {id: appartment.to_param, appartment: new_attributes}, session: valid_session
        appartment.reload
        expect(appartment.name).to eq('Hiboux')
      end

      it "assigns the requested appartment as @appartment" do
        appartment = Appartment.create! valid_attributes
        put :update,  {id: appartment.to_param, appartment: valid_attributes}, session: valid_session
        expect(assigns(:appartment)).to eq(appartment)
      end

      it "redirects to the appartment" do
        appartment = Appartment.create! valid_attributes
        put :update,  {id: appartment.to_param, appartment: valid_attributes}, session: valid_session
        expect(response).to redirect_to(appartment)
      end
    end

    context "with invalid params" do
      it "assigns the appartment as @appartment" do
        appartment = Appartment.create! valid_attributes
        put :update,  {id: appartment.to_param, appartment: invalid_attributes}, session: valid_session
        expect(assigns(:appartment)).to eq(appartment)
      end

      it "re-renders the 'edit' template" do
        appartment = Appartment.create! valid_attributes
        put :update,  {id: appartment.to_param, appartment: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested appartment" do
      appartment = Appartment.create! valid_attributes
      expect {
        delete :destroy,  {id: appartment.to_param}, session: valid_session
      }.to change(Appartment, :count).by(-1)
    end

    it "redirects to the appartments list" do
      appartment = Appartment.create! valid_attributes
      delete :destroy, {id: appartment.to_param}, session: valid_session
      expect(response).to redirect_to(appartments_url)
    end
  end

end
