require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MonthsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Month. As you add validations to Month, be sure to
  # adjust the attributes here as well.
  let(:chalet) { create :house }
  let(:panda) { create :appartment, house_id: chalet.id }
  let(:valid_attributes) { attributes_for :month, appartment_id: panda.id }

  let(:invalid_attributes) { attributes_for :month, name: '' }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MonthsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  login_admin
  describe "GET #index" do
    it "assigns all months as @months" do
      month = Month.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:months)).to eq([month])
    end
  end

  describe "GET #show" do
    it "assigns the requested month as @month" do
      month = Month.create! valid_attributes
      get :show,  {id: month.to_param}, session: valid_session
      expect(assigns(:month)).to eq(month)
    end
  end

  describe "GET #new" do
    it "assigns a new month as @month" do
      get :new,  {}, session: valid_session
      expect(assigns(:month)).to be_a_new(Month)
    end
  end

  describe "GET #edit" do
    it "assigns the requested month as @month" do
      month = Month.create! valid_attributes
      get :edit,  {id: month.to_param}, session: valid_session
      expect(assigns(:month)).to eq(month)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Month" do
        expect {
          post :create,  {month: valid_attributes}, session: valid_session
        }.to change(Month, :count).by(1)
      end

      it "assigns a newly created month as @month" do
        post :create,  {month: valid_attributes}, session: valid_session
        expect(assigns(:month)).to be_a(Month)
        expect(assigns(:month)).to be_persisted
      end

      it "redirects to the created month" do
        post :create,  {month: valid_attributes}, session: valid_session
        expect(response).to redirect_to(house_path(Month.last.appartment.house.id))
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved month as @month" do
        post :create,  {month: invalid_attributes}, session: valid_session
        expect(assigns(:month)).to be_a_new(Month)
      end

      it "re-renders the 'new' template" do
        post :create,  {month: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) { attributes_for :month, name: 'January' }

      it "updates the requested month" do
        month = Month.create! valid_attributes
        put :update,  {id: month.to_param, month: new_attributes}, session: valid_session
        month.reload
        expect(month.name).to eq('January')
      end

      it "assigns the requested month as @month" do
        month = Month.create! valid_attributes
        put :update, {id: month.to_param, month: valid_attributes}, session: valid_session
        expect(assigns(:month)).to eq(month)
      end

      it "redirects to the month" do
        month = Month.create! valid_attributes
        put :update, {id: month.to_param, month: valid_attributes}, session: valid_session
        expect(response).to redirect_to(house_path(month.appartment.house.id))
      end
    end

    context "with invalid params" do
      it "assigns the month as @month" do
        month = Month.create! valid_attributes
        put :update,  {id: month.to_param, month: invalid_attributes}, session: valid_session
        expect(assigns(:month)).to eq(month)
      end

      it "re-renders the 'edit' template" do
        month = Month.create! valid_attributes
        put :update,  {id: month.to_param, month: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested month" do
      month = Month.create! valid_attributes
      expect {
        delete :destroy,  {id: month.to_param}, session: valid_session
      }.to change(Month, :count).by(-1)
    end

    it "redirects to the months list" do
      month = Month.create! valid_attributes
      delete :destroy, {id: month.to_param}, session: valid_session
      expect(response).to redirect_to(house_path(month.appartment.house.id))
    end
  end

end
