require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe WeeksController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Week. As you add validations to Week, be sure to
  # adjust the attributes here as well.

  let(:chalet) { create :house }
  let(:panda) { create :appartment, house_id: chalet.id }
  let(:december) { create :month, appartment_id: panda.id }

  let(:valid_attributes) { attributes_for :week, month_id: december.id }

  let(:invalid_attributes) { attributes_for :week, from: '', to: 'a string' }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WeeksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  login_admin

  describe "GET #index" do
    it "assigns all weeks as @weeks" do
      week = Week.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:weeks)).to eq([week])
    end
  end

  describe "GET #show" do
    it "assigns the requested week as @week" do
      week = Week.create! valid_attributes
      get :show,  {id: week.to_param}, session: valid_session
      expect(assigns(:week)).to eq(week)
    end
  end

  describe "GET #new" do
    it "assigns a new week as @week" do
      get :new,  {}, session: valid_session
      expect(assigns(:week)).to be_a_new(Week)
    end
  end

  describe "GET #edit" do
    it "assigns the requested week as @week" do
      week = Week.create! valid_attributes
      get :edit,  {id: week.to_param}, session: valid_session
      expect(assigns(:week)).to eq(week)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Week" do
        expect {
          post :create,  {week: valid_attributes}, session: valid_session
        }.to change(Week, :count).by(1)
      end

      it "assigns a newly created week as @week" do
        post :create,  {week: valid_attributes}, session: valid_session
        expect(assigns(:week)).to be_a(Week)
        expect(assigns(:week)).to be_persisted
      end

      it "redirects to the created week" do
        post :create,  {week: valid_attributes}, session: valid_session
        expect(response).to redirect_to(house_path(Week.last.month.appartment.house.id))
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved week as @week" do
        post :create,  {week: invalid_attributes}, session: valid_session
        expect(assigns(:week)).to be_a_new(Week)
      end

      it "re-renders the 'new' template" do
        post :create,  {week: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) { attributes_for :week, from: 12, to: 20 }

      it "updates the requested week" do
        week = Week.create! valid_attributes
        put :update,  {id: week.to_param, week: new_attributes}, session: valid_session
        week.reload
        expect(week.from).to eq(12)
        expect(week.to).to eq(20)
      end

      it "assigns the requested week as @week" do
        week = Week.create! valid_attributes
        put :update,  {id: week.to_param, week: valid_attributes}, session: valid_session
        expect(assigns(:week)).to eq(week)
      end

      it "redirects to the week" do
        week = Week.create! valid_attributes
        put :update,  {id: week.to_param, week: valid_attributes}, session: valid_session
        expect(response).to redirect_to(house_path(week.month.appartment.house.id))
      end
    end

    context "with invalid params" do
      it "assigns the week as @week" do
        week = Week.create! valid_attributes
        put :update,  {id: week.to_param, week: invalid_attributes}, session: valid_session
        expect(assigns(:week)).to eq(week)
      end

      it "re-renders the 'edit' template" do
        week = Week.create! valid_attributes
        put :update,  {id: week.to_param, week: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested week" do
      week = Week.create! valid_attributes
      expect {
        delete :destroy,  {id: week.to_param}, session: valid_session
      }.to change(Week, :count).by(-1)
    end

    it "redirects to the weeks list" do
      week = Week.create! valid_attributes
      delete :destroy,  {id: week.to_param}, session: valid_session
      expect(response).to redirect_to(weeks_url)
    end
  end

end
